theme: jekyll-theme-cayman
repository_name: centinum
title: centinum
emoji: ⭕
description:
  A central configuration manager for multiple repositories, enabling unified
  settings, streamlined workflows, and simplified maintenance across projects.
show_downloads: true
collections:
  pages:
    output: true # Generates HTML files for each file
    permalink: /:path/ # URL structure for collection items
