# ------------------------------------------------------------------------------
# Prettier configuration file
# https://prettier.io
# ------------------------------------------------------------------------------

proseWrap: "always"
